@QuickApp.Server_HostAddress = https://localhost:7085
@QuickApp.Client_HostAddress = https://localhost:4200
@username = admin
@password = tempP@ss123

#### This file enables you to test the APIs of QuickApp.
#### You can also test the APIs with Swagger by appending "/swagger"" to the home url or by using postman
#### See https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0 for more info on http files


###################################################
### Login to get access token
###################################################
# @name login
POST {{QuickApp.Server_HostAddress}}/connect/token
Content-Type: application/x-www-form-urlencoded

client_id=swagger_ui&grant_type=password&username={{username}}&password={{password}}


###################################################
### User APIs
###################################################

### Get all users
GET {{QuickApp.Server_HostAddress}}/api/account/users
Accept: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

### Get current user
GET {{QuickApp.Server_HostAddress}}/api/account/users/me
Accept: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

### Register new user test_user_1
POST {{QuickApp.Server_HostAddress}}/api/account/users
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json

{
    "userName": "test_user_1",
    "email": "test_user_1@ebenmonney.com",
    "isEnabled": true,
    "newPassword": "testP@ss123",
    "roles": ["administrator"]
}

### Get newly registered user with username "test_user_1"
# @name testUser1
GET {{QuickApp.Server_HostAddress}}/api/account/users/username/test_user_1
Accept: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

### Update user with a specific id. E.g. test_user_1's id
PUT {{QuickApp.Server_HostAddress}}/api/account/users/{{testUser1.response.body.$.id}}
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json

{
    "userName": "testUser1",
    "fullName": "My New Fullname",
    "email": "testUser1@ebenmonney.com",
    "isEnabled": true,
    "isLockedOut": false,
    "jobTitle": "Dr.",
    "phoneNumber": "+2 (456) 123-789",
    "roles": ["administrator"]
}

### Delete user with a specific id. E.g. testUser1's id
DELETE {{QuickApp.Server_HostAddress}}/api/account/users/{{testUser1.response.body.$.id}}
Authorization: Bearer {{login.response.body.$.access_token}}


###################################################
### Role APIs
###################################################

### Get all roles
GET {{QuickApp.Server_HostAddress}}/api/account/roles
Accept: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

### Register new role
POST {{QuickApp.Server_HostAddress}}/api/account/roles
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json

{
    "name": "test_role_1",
    "description": "This is the Test Role 1"
}

### Get newly registered role with role name "test_role_1"
# @name testRole1
GET {{QuickApp.Server_HostAddress}}/api/account/roles/name/test_role_1
Accept: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

### Get role with a specific id. E.g. test_role_1's id
GET {{QuickApp.Server_HostAddress}}/api/account/roles/{{testRole1.response.body.$.id}}
Accept: application/json
Authorization: Bearer {{login.response.body.$.access_token}}

### Update role with a specific id. E.g. test_role_1's id
PUT {{QuickApp.Server_HostAddress}}/api/account/roles/{{testRole1.response.body.$.id}}
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json

{
  "name": "test_role_123",
  "description": "New name and description for test_role_1",
  "permissions": [
    {"value": "users.view"},
    {"value": "roles.view"}
  ]
}

### Delete role with a specific id. E.g. test_role_1's id
DELETE {{QuickApp.Server_HostAddress}}/api/account/roles/{{testRole1.response.body.$.id}}
Authorization: Bearer {{login.response.body.$.access_token}}


###################################################
### Customer APIs
###################################################

### Get dummy customers
GET {{QuickApp.Client_HostAddress}}/api/Customer
Accept: */*

### ... Add more APIs here