@QuickApp.Server_HostAddress = https://localhost:7085
@QuickApp.Client_HostAddress = https://localhost:4200
@AccessToken = Paste_access_token_here

#### This file enables you to test the APIs of QuickApp.
#### You can also test the APIs with Swagger by appending "/swagger"" to the home url or by using postman
#### See https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0 for more info on http files


###################################################
### Login to get access token
###################################################
POST {{QuickApp.Server_HostAddress}}/connect/token
Content-Type: application/x-www-form-urlencoded

client_id=swagger_ui&grant_type=password&username=admin&password=tempP@ss123


###################################################
### User APIs
###################################################

### Get all users
GET {{QuickApp.Server_HostAddress}}/api/account/users
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Get current user
GET {{QuickApp.Server_HostAddress}}/api/account/users/me
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Register new user
POST {{QuickApp.Server_HostAddress}}/api/account/users
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "userName": "test_1",
    "email": "test_1@ebenmonney.com",
    "isEnabled": true,
    "newPassword": "testP@ss123",
    "roles": ["administrator"]
}

### Get newly registered user with username "test_1"
GET {{QuickApp.Server_HostAddress}}/api/account/users/username/test_1
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Update user with a specific id
PUT {{QuickApp.Server_HostAddress}}/api/account/users/Paste_user_id_here
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "userName": "test_1",
    "fullName": "My New Fullname",
    "email": "test_1@ebenmonney.com",
    "isEnabled": true,
    "isLockedOut": false,
    "jobTitle": "Dr.",
    "phoneNumber": "+2 (456) 123-789",
    "roles": ["administrator"]
}

### Delete user with a specific id
DELETE {{QuickApp.Server_HostAddress}}/api/account/users/Paste_user_id_here
Authorization: Bearer {{AccessToken}}


###################################################
### Role APIs
###################################################

### Get all roles
GET {{QuickApp.Server_HostAddress}}/api/account/roles
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Get role with a specific id
GET {{QuickApp.Server_HostAddress}}/api/account/roles/Paste_role_id_here
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Register new role
POST {{QuickApp.Server_HostAddress}}/api/account/roles
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "name": "test_1",
    "description": "Test role 1"
}

### Get newly registered role with role name "test_1"
GET {{QuickApp.Server_HostAddress}}/api/account/roles/name/test_1
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Update role with a specific id
PUT {{QuickApp.Server_HostAddress}}/api/account/roles/Paste_role_id_here
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "test_123",
  "description": "New test role 1 description",
  "permissions": [
    {"value": "users.view"},
    {"value": "roles.view"}
  ]
}


### Delete role with a specific id
DELETE {{QuickApp.Server_HostAddress}}/api/account/roles/Paste_role_id_here
Authorization: Bearer {{AccessToken}}


###################################################
### Customer APIs
###################################################

### Get dummy customers
GET {{QuickApp.Client_HostAddress}}/api/Customer
Accept: */*

### ... Add more APIs here